### ISSUE TITLE
Issue on step "Run backend simulator  cd nodejs && npm install node index.js"

### ISSUE THREAD

**Issue by Guinnessstache** [OriginTrail/AAP-market-simulator#6]
ladmin@DESKTOP-MC01F6K:~/AAP-market-simulator/nodejs$ node index.js
/home/ladmin/AAP-market-simulator/nodejs/modules/utilities/utilities.js:121
        const lockFilePath = `${path.split('.').slice(0, -1).join('.')}.lock`;
                                     ^

TypeError: Cannot read property 'split' of undefined
    at Function.changeFileAttributeAtomic (/home/ladmin/AAP-market-simulator/nodejs/modules/utilities/utilities.js:121:38)
    at Object.<anonymous> (/home/ladmin/AAP-market-simulator/nodejs/index.js:10:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by bottomshorter** [comment]
Could it be that here is a missing .env file? I do not see one after cloning the repo. 

I added a .env file and it got rid of the error. 

However, nothing comes in terminal after I execute it again. After loading the front-end end, I cannot interact with adding nodes/saving the new name, running the simulation, even after making the .env file using contents:

`CONFIG_PATH = nodejs/config/config.json`

**Comment by alko89** [comment]
Try exporting the config path `export CONFIG_PATH=nodejs/config/config.json`

**Comment by bottomshorter** [comment]
> Try exporting the config path `export CONFIG_PATH=nodejs/config/config.json`

within the /nodejs/index.js file?

**Comment by bottomshorter** [comment]
> > Try exporting the config path `export CONFIG_PATH=nodejs/config/config.json`
> 
> not sure where to export the CONFIG_PATH from? as it pulls the CONFIG_PATH from the .env right, so you cant export it, only define the variables used defined in .env then import via index.js?

**Comment by alko89** [comment]
Before you start node in your console, execute the export, this will set the CONFIG_PATH environment (it probably also works with an env file).
You can check if the environment variable set by using `echo $CONFIG_PATH` on Linux or Mac, I don't know how to do it in powershell or cmd on Windows though.

**Comment by kotlarmilos** [comment]
You should add the following line in your .env file:

`CONFIG_PATH = nodejs/config/config.json`
